name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Enable Web
        run: flutter config --enable-web

      - name: Install dependencies
        run: flutter pub get
        working-directory: .

      - name: Build Web
        run: flutter build web --base-href "/stardust_vault/" --verbose
        working-directory: .

      - name: Verify Web
        run: ls -R ./build/web
        working-directory: .

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build/web

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
